#pragma once

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"

#include "esp_err.h"
#include "esp_log.h"
#include "esp_system.h"

#include "esp_netif.h"
#include "esp_wifi.h"
#include "esp_http_client.h"
#include "esp_ota_ops.h"

#include "espnow.h"
#include "espnow_ota.h"
// #include "espnow_storage.h"
#include "espnow_utils.h"

// #include "protocol_examples_common.h"

#define OTA_DATA_PAYLOAD_LEN 1024
#define MAX_HTTP_ATTEMPTS_COUNT 5

/* The event group allows multiple bits for each event, the relevant events are:
 * - getting connected to the AP with an IP
 * - failed to connect after the maximum amount of retries */
#define WIFI_CONNECTED_BIT BIT0
#define WIFI_FAIL_BIT      BIT1

#if CONFIG_EXAMPLE_WIFI_SCAN_METHOD_FAST
#define EXAMPLE_WIFI_SCAN_METHOD WIFI_FAST_SCAN
#elif CONFIG_EXAMPLE_WIFI_SCAN_METHOD_ALL_CHANNEL
#define EXAMPLE_WIFI_SCAN_METHOD WIFI_ALL_CHANNEL_SCAN
#endif

#if CONFIG_EXAMPLE_WIFI_CONNECT_AP_BY_SIGNAL
#define EXAMPLE_WIFI_CONNECT_AP_SORT_METHOD WIFI_CONNECT_AP_BY_SIGNAL
#elif CONFIG_EXAMPLE_WIFI_CONNECT_AP_BY_SECURITY
#define EXAMPLE_WIFI_CONNECT_AP_SORT_METHOD WIFI_CONNECT_AP_BY_SECURITY
#endif

#if CONFIG_EXAMPLE_WIFI_AUTH_OPEN
#define EXAMPLE_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_OPEN
#elif CONFIG_EXAMPLE_WIFI_AUTH_WEP
#define EXAMPLE_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WEP
#elif CONFIG_EXAMPLE_WIFI_AUTH_WPA_PSK
#define EXAMPLE_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_PSK
#elif CONFIG_EXAMPLE_WIFI_AUTH_WPA2_PSK
#define EXAMPLE_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_PSK
#elif CONFIG_EXAMPLE_WIFI_AUTH_WPA_WPA2_PSK
#define EXAMPLE_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_WPA2_PSK
#elif CONFIG_EXAMPLE_WIFI_AUTH_WPA2_ENTERPRISE
#define EXAMPLE_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_ENTERPRISE
#elif CONFIG_EXAMPLE_WIFI_AUTH_WPA3_PSK
#define EXAMPLE_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA3_PSK
#elif CONFIG_EXAMPLE_WIFI_AUTH_WPA2_WPA3_PSK
#define EXAMPLE_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_WPA3_PSK
#elif CONFIG_EXAMPLE_WIFI_AUTH_WAPI_PSK
#define EXAMPLE_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WAPI_PSK
#endif


#define WIFI_SCAN_METHOD EXAMPLE_WIFI_SCAN_METHOD
#define WIFI_SORT_METHOD EXAMPLE_WIFI_CONNECT_AP_SORT_METHOD
#define WIFI_THRESHOLD_RSSI CONFIG_EXAMPLE_WIFI_SCAN_RSSI_THRESHOLD
#define WIFI_THRESHOLD_AUTHMODE EXAMPLE_WIFI_SCAN_AUTH_MODE_THRESHOLD
#define WIFI_RETRY_LIMIT CONFIG_EXAMPLE_WIFI_CONN_MAX_RETRY

#define ENOW_SCAN_RETRY_LIMIT 10

#define ESPNOW_CHANNEL 6

#define DELAY(x) vTaskDelay(pdMS_TO_TICKS(x))

esp_err_t connect_wifi_ap(void);

esp_err_t connection_init(void);

esp_err_t ota_firmware_fetch(const char *ota_url);

esp_err_t ota_firmware_send(void);
